apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../juno"

images:
  - name: ghcr.io/douyu/juno-admin
    newName: ghcr.io/douyu/juno-admin-dev
  - name: ghcr.io/douyu/juno-agent
    newName: ghcr.io/douyu/juno-agent-dev
  - name: mysql
    newName: ghcr.io/douyu/mysql-dev

patches:
  - target:
      kind: Deployment
      name: juno-agent
    path: juno-agent.yaml
